[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
default = false
secondary = true

[tool.poetry.dependencies]
python = "3.11.*"
torch = {version = "^2.0.0+cpu", source = "pytorch-cpu"}

[tool.poetry.dev-dependencies]
numpy = "1.*.*"

[tool.mypy]
python_version = "3.11"
